<?php
return array(
    'zh' => 'pages/zh/index.php',
    'zh/about-us' => 'pages/zh/about-us.php',
    'zh/product' => 'pages/zh/product.php',
    'zh/new' => 'pages/zh/new.php',
    'zh/recipe' => 'pages/zh/recipe.php',
    'zh/brand' => 'pages/zh/brand.php',
    'zh/blog' => 'pages/zh/blog.php',
    'zh/certification' => 'pages/zh/certification.php',
    'zh/cooperation' => 'pages/zh/cooperation.php',
    'zh/contact' => 'pages/zh/contact.php',
    'zh/bag' => 'pages/zh/bag.php',
    'en' => 'pages/en/index.php',
    'en/about-us' => 'pages/en/about-us.php',
    'en/product' => 'pages/en/product.php',
    'en/new' => 'pages/en/new.php',
    'en/recipe' => 'pages/en/recipe.php',
    'en/brand' => 'pages/en/brand.php',
    'en/blog' => 'pages/en/blog.php',
    'en/certification' => 'pages/en/certification.php',
    'en/cooperation' => 'pages/en/cooperation.php',
    'en/contact' => 'pages/en/contact.php',
    'en/bag' => 'pages/en/bag.php',
);
