<?php
return array(
    'zh/bag' => 'pages/zh/bag.php',
    'zh/caviar' => 'pages/zh/caviar.php',
    'zh/certification' => 'pages/zh/certification.php',
    'zh/contact' => 'pages/zh/contact.php',
    'zh/gifting' => 'pages/zh/gifting.php',
    'zh' => 'pages/zh/index.php',
    'zh/journal' => 'pages/zh/journal.php',
    'zh/news' => 'pages/zh/news.php',
    'zh/rituals' => 'pages/zh/rituals.php',
    'en/bag' => 'pages/en/bag.php',
    'en/certification' => 'pages/en/certification.php',
    'en/contact' => 'pages/en/contact.php',
    'en/gifting' => 'pages/en/gifting.php',
    'en' => 'pages/en/index.php',
    'en/journal' => 'pages/en/journal.php',
    'en/news' => 'pages/en/news.php',
    'en/products' => 'pages/en/products.php',
    'en/rituals' => 'pages/en/rituals.php',
);
